#!/bin/bash
numerofile=$(ls | grep "linux-5" | grep -E zst$ | wc -l)
deletesig=$(ls /var/cache/pacman/pkg/ | grep -E sig$)
deletefile=$(ls /var/cache/pacman/pkg/ | grep "linux-5" | grep -E zst$ | head -$(($numerofile-1)))
rm -r $deletefile  
rm -r $deletesig
if [ $numerofile -eq 1 ] 
then
exit 1 
if [ $numerofile -eq 0 ] 
then
deletesig=$(ls /var/cache/pacman/pkg | grep "linux-6" | grep -E sig$)
numerofile=$(ls /var/cache/pacman/pkg | grep "linux-6" | grep -E zst$ | wc -l)
deletefile=$(ls /var/cache/pacman/pkg | grep "linux-6" | grep -E zst$ | head -$(($numerofile-1)))
rm -r $deletefile 
rm -r $deletesig
fi
