#!/bin/bash
filenumber=$(ls | grep "linux-5" | wc -l)
deletefile=$(ls /var/cache/pacman/pkg/ | grep "linux-5" | head -$(($filenumber-1)))
cd /var/cache/pacman/pkg && rm -r $deletefile  
if [ $filenumber -eq 1 ] 
then
deletefile=$(ls /var/cache/pacman/pkg/ | grep "linux-5" | head -$filenumber)
cd /var/cache/pacman/pkg && rm -r $deletefile 
fi
if [ $filename -eq 0 ] 
then
numerofile=$(ls /var/cache/pacman/pkg | grep "linux-6" | wc -l)
deletefile=$(ls /var/cache/pacman/pkg | grep "linux-6" | head -$(($filename-1)))
cd /var/cache/pacman/pkg && rm -r $deletefile 
fi
